# Base configs
baseurl: "http://axen46.github.io/Clicks"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Apratim Sarkar"
subtitle: "See the world through my eyes!"
author: "Apratim Sarkar"
header:
 title: "Photography"
 subtitle: "by Apratim Sarkar"
footer:
 name: "Hey there, my name is Apratim"
 bio: "I am a developer and a tech aficionado from India."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/Axen47"
  twitter: "https://www.twitter.com/ApratimSarkar5"
  instagram: "https://www.instagram.com/axen_46"
  linkedin: "https://in.linkedin.com/in/apratim-sarkar-837897135"
  github: "https://www.github.com/axen46"
